Pedropaulo/development/ontouml models
unibz-core/ontouml-models pull request #2
Opened 2021-11-04 16:43 UTC by pedropaulofb

All required files for barcelos2013ontology are already available.

2021-11-06 16:33 UTC, claudenirmf requested changes
You must update the names of your files according to the repository's instructions.

We have not required this, but it be nice if the names of the new diagrams matched the names of the original ones.

I like that your screenshots of diagrams kept the figures' labels.

When I tried opening your VP project the diagrams were weird... Can you check whether you committed the most recent version of the project?
![image](https://user-images.githubusercontent.com/12445213/140616875-3bff8517-ddf5-480f-8496-999b40ec1b1e.png)

The package structure of you VP project is inconsistent, please fix that.

2021-11-06 16:37 UTC, claudenirmf commented
It would also be nice if your commit titles were clearer about it was done, for example, "adds all required files".

2021-11-06 16:42 UTC, claudenirmf commented
Remember to pass the original diagrams through [tinypng](https://tinypng.com/) if you haven't done so.

2021-11-09 13:29 UTC, pedropaulofb commented
Thank you for your considerations. I believe that now the data is as
expected.

Kind regards - Cordiali saluti - Atenciosamente,
Pedro Paulo Favato Barcelos


Em sáb., 6 de nov. de 2021 às 17:42, Claudenir Fonseca <
***@***.***> escreveu:

> Remember to pass the original diagrams through tinypng
> <https://tinypng.com/> if you haven't done so.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/unibz-core/ontouml-models/pull/2#issuecomment-962477396>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACB5Y32B3N4SWKTCXKIP66LUKVLG7ANCNFSM5HL4SLTA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-10 14:58 UTC, claudenirmf commented on barcelos2013ontology/references.bib
> +  title={An Ontology Reference Model for Normative Acts.},
This `bib` entry is wrong/incomplete. Please double get how to cite CEUR papers (http://ceur-ws.org/Vol-1041/).

2021-11-15 16:20 UTC, claudenirmf approved these changes

2021-11-15 16:23 UTC, claudenirmf commented
Thanks for the nice work.

A feedback for next time, though: when finishing your revisions, answer my review confirming your changes for every comment I made. See this answer I got on another PR: https://github.com/unibz-core/ontouml-models/pull/3#issuecomment-967117725

2021-11-15 16:23 UTC, merged