Hi, this is the first commit, I hope you'll see it
unibz-core/ontouml-models pull request #22
Opened 2021-12-14 13:21 UTC by AndrasKomaromi

2021-12-14 15:08 UTC, claudenirmf commented on plato-ontology2019/metadata.yml
> +  github-repo: https://github.com/unibz-core/UFO-S
In the `urls` field, you should have the URL to your blog instead, something like this:

```yaml
urls:
 blog: https://github.com/unibz-core/UFO-S
```

2021-12-14 15:09 UTC, claudenirmf commented on plato-ontology2019/metadata.yml
> +main-source: https://philosophy-models.blog/
In the `main-source` field, you should have the bib id of the main reference:

```yaml
main-source: plato-ontology2019
```

2021-12-14 16:02 UTC, claudenirmf requested changes
@AndrasKomaromi, thank you very much for your contribution. Here goes my observations on your pull request.

 - Since you are submitting the original ontology files, you should only use the `original diagrams` folder and leave the `new diagrams` empty.
 - You should resize some classes such that we can see their attrbitues as well.

![Screen Shot 2021-12-14 at 16 26 14](https://user-images.githubusercontent.com/12445213/146027586-1aaf0511-d2b4-4277-b15e-869f8c612d07.png)

 - Your ontology file contains an empty constraint. You might want to delete that.
 - Please, make sure that the last thing you do before committing is exporting the JSON file, otherwise it may not contain changes made in the Visual Paradigm project.

2021-12-14 18:05 UTC, AndrasKomaromi commented
Hi, I finished for today, thanks a lot for the possibility! Let me know if there are any problems with the new uploaded ontologies.

2022-03-11 13:58 UTC, Matt-81 approved these changes

2022-03-11 13:59 UTC, Matt-81 approved these changes

2022-03-11 15:02 UTC, claudenirmf approved these changes

2022-03-17 10:20 UTC, merged