Add model van2020ontological
unibz-core/ontouml-models pull request #24
Opened 2021-12-14 13:37 UTC by Isadoravsousa

2021-12-14 17:36 UTC, claudenirmf requested changes
Thank you for your contribution, @Isadoravsousa! Please address the following change requests before we can merge it:

- The metadata, references, and ontology files were named as `metadata.yaml.txt`, `references.bib.txt`, and `ontology.vpp.vpp`. Please remove the trailing `.txt` and `.vpp` extensions. On Windows you have to enable the option to see the files' extensions.
- Please complement the information on your references file with the bib entry from the publisher:

```bib
@INPROCEEDINGS{9140251,
  author={van Wingerde, M.E.M. and Weigand, H.},
  booktitle={2020 IEEE 22nd Conference on Business Informatics (CBI)}, 
  title={An ontological analysis of artifact-centric business processes managed by smart contracts}, 
  year={2020},
  volume={1},
  number={},
  pages={231-240},
  doi={10.1109/CBI49978.2020.00032}}
```

- Please make sure that the last thing you did was exporting the JSON file, otherwise it may not be up to date with the Visual Paradigm project.

2021-12-14 17:36 UTC, claudenirmf commented on van2020ontological/references.bib.txt
> +  booktitle={2020 IEEE 22nd Conference on Business Informatics (CBI)},
If you don't sorround acronyms with curly brackets, they'll be processed and camel case by LaTex, please change this line to `booktitle={2020 {IEEE} 22nd Conference on Business Informatics ({CBI})}`.

2021-12-14 17:36 UTC, claudenirmf commented on van2020ontological/references.bib.txt
> +  organization={IEEE}
`organization={{IEEE}}`

2021-12-14 17:36 UTC, claudenirmf commented on van2020ontological/metadata.yaml.txt
> +title: An ontological analysis of artifact-centric business processes managed by smart contracts
We expect the name of ontology here instead of the title of the paper. If they have a name for the ontology in the paper, please use it instead.

2021-12-14 17:36 UTC, claudenirmf commented on van2020ontological/metadata.yaml.txt
> +editorial-notes:
I thought there were some observations you should add here. But ignore my comment if that is not the case.

2021-12-14 17:36 UTC, claudenirmf commented on van2020ontological/metadata.yaml.txt
> +  github:
You should remove the github line.

2021-12-14 18:01 UTC, Isadoravsousa commented on van2020ontological/references.bib.txt
> +  organization={IEEE}
We decided to delete this line.

2021-12-14 18:10 UTC, Isadoravsousa commented on van2020ontological/metadata.yaml.txt
> +title: An ontological analysis of artifact-centric business processes managed by smart contracts
There isn't.

2022-03-10 23:20 UTC, claudenirmf approved these changes

2022-03-10 23:21 UTC, merged