add ontology "Modular Construction Ontology"
unibz-core/ontouml-models pull request #25
Opened 2021-12-14 13:44 UTC by TvanEe

This ontology is still under development in the context of my PDEng at the University of Twente

2021-12-14 16:36 UTC, claudenirmf commented
Hi @TvanEe, thank you for your contribution!

So, because you kept working after opening your pull request, both ontologies are here (vanEe2021Modular and fumagali2015the). To separate them, we would have to have created a new branch, but that is ok now. Just let me knnow if both vanEe2021Modular and fumagali2015the are ready to be reviewed.

2021-12-15 07:23 UTC, TvanEe commented
Hi @claudenirmf, 

Sorry about that, not sure what I did wrong, but both are ready to be reviewed.

2022-03-11 13:00 UTC, Matt-81 approved these changes

2022-03-11 13:37 UTC, claudenirmf requested changes
This branch must not be merged for now. There is a potential merge issue to be clarified first

2022-03-21 15:27 UTC, merged