Add model: Grain Production Ontology
unibz-core/ontouml-models pull request #3
Opened 2021-11-05 16:01 UTC by tgoprince

2021-11-11 13:46 UTC, claudenirmf requested changes
Could you please set the navigability on the source of the associations to `Unspecified`? Even though the original diagrams do not have a direction, the serialization will assume one. This is a case where our documentation of a model may affect its original semantics and, if this unavoidable, we should at the very least be clear about it. I also suggest adding that to the folder's metadata (i.e., to the `editorial-notes`).

Still on the same note, maybe we should include the default cardinality to all models as well because, in case we are committing to something other than the author's original conceptualization, at least we are being clear about it.

Your two most recent commits change the `vpp` but you did not upload a new version of the JSON serialization. Is it up to date?

2021-11-11 13:46 UTC, claudenirmf commented on neves2021ontology/references.bib
> +  booktitle={2021 IEEE 15th International Conference on Semantic Computing (ICSC)},
Please, add brackets surrounding capitalized terms (e.g., "IEEE").

2021-11-12 13:19 UTC, tgoprince commented on neves2021ontology/references.bib
> +  booktitle={2021 IEEE 15th International Conference on Semantic Computing (ICSC)},
Done.

2021-11-15 15:11 UTC, claudenirmf approved these changes

2021-11-15 15:12 UTC, merged