Updates UFO-S ontology (nardi2015commitment)
unibz-core/ontouml-models pull request #4
Opened 2021-11-06 16:10 UTC by claudenirmf

This pull requests updates documentation of the UFO-S ontology.

This PR is partially solves #1 . 

Additionally, it also includes minor fixes to the repository's README file.

2021-11-10 18:13 UTC, Matt-81 reviewed
I would make more explicit the mapping between original and output diagrams. We have 13 files as original diagrams and 3 files as new diagrams.

Did you use the information from all the 13 inputs to generate the 3 final outputs?

2021-11-10 18:21 UTC, Matt-81 reviewed
Your new diagrams look very cool =) Maybe we can provide some more constraints on how to design the diagrams. Now we just say to stick with the original diagram as much as possible, but we may add some info like the ones you sent me (e.g., paint through labels, orthogonal vs. organic, ...)

2021-11-10 18:30 UTC, Matt-81 requested changes
Maybe in the .bib is better to arrange the refs in chronological order. Or maybe you arranged them according to different criteria?

2021-11-11 07:54 UTC, claudenirmf commented
> Did you use the information from all the 13 inputs to generate the 3 final outputs?

I have used the diagram number to identify the relationship between original and old diagrams.

> Maybe we can provide some more constraints on how to design the diagrams.

Sure, let's discuss that on the meeting

> Maybe in the .bib is better to arrange the refs in chronological order.

I don't think this makes any difference since the file only contains a few reference. But I'm open to be convinced that this needs to be enforced.

2021-11-11 15:16 UTC, claudenirmf commented on nardi2015commitment/metadata.yml
> +title: UFO-S
This is not the correct name

2021-11-15 15:51 UTC, claudenirmf commented
Remember to use "Squash and Merge" when accepting this PR.

![Screen Shot 2021-11-15 at 16 50 56](https://user-images.githubusercontent.com/12445213/141812149-46d50cfa-8ed4-4bfb-8c6b-bd797ed335cd.png)

2021-11-16 07:02 UTC, merged