Mattia/development/ontouml models
unibz-core/ontouml-models pull request #8
Opened 2021-11-10 08:02 UTC by Matt-81

Files updated according to what was discussed at the last meeting (5.11.2021)

2021-11-10 15:08 UTC, claudenirmf commented on niederkofler2019knowledge/references.bib
> +  title={Knowledge Models for Diagnosing Postharvest Diseases of Apples.},
This `bib` entry is wrong/incomplete. Please double-check how to cite CEUR papers (http://ceur-ws.org/Vol-2518/).

2021-11-10 15:30 UTC, claudenirmf requested changes
Did you pass the screenshots of the original diagrams through [TinyPng](https://tinypng.com/)? The file sizes are a bit larger than what I expected.

Did you remember updating the JSON serialization after the lastest changes to the `vpp` file?

You have empty diagrams on your `vpp` file. Please remove them.

Please, enable the option "Paint Through Label" on your diagrams.
![Screen Shot 2021-11-10 at 16 15 10](https://user-images.githubusercontent.com/12445213/141139739-7c72e21f-bc4c-4024-a2e6-88f102072482.png)

Great attention to the original (mis-)spellings of names =)

Some associations are missing a clear direction. On associations that do not have that set automatically, please set the navigability to `Unspecified` on the source side.

You can set the _Connector Style_ to `Curve` in order to make the relations and generalizations smother, like in the original diagrams.
![Screen Shot 2021-11-10 at 16 22 03](https://user-images.githubusercontent.com/12445213/141140905-608dc708-6f49-4436-9911-7a526ffd86bc.png)

Don't you think that it would be best to name the diagrams inside the `vpp` file "diagram1", "diagram2", and so? This way it will be easy to export them with their correct names.

Can you make screenshots of the original diagrams keeping their labels (e.g., "Figure 1. Taxonomy of Apple Aspect.")?

Could you please name your commits in a clearer way? For example, "Updates diagrams names". This way it is easier for us to know what you did at each step and you are encouraged to make smaller commits and make them more often.

2021-11-10 17:19 UTC, Matt-81 commented
Thanks, @claudenirmf! I updated the files following your feedback. Still have some minor doubts, let's solve them tomorrow.

2021-11-15 16:02 UTC, claudenirmf commented on niederkofler2019knowledge/metadata.yaml
> +editorial-notes:
The way you specified this field makes it into an array of strings rather than a single string. You could have written like this insteand:

```yaml
editorial-notes: Associations have no direction (e.g, characterization, first diagram); how to model classification types; how to model formal associations.
```

Also, I need you to better explain these notes.

2021-11-15 16:04 UTC, claudenirmf requested changes
You have missed a couple of stereotypes on associations, like this characterization on `diagram3`:

![Screen Shot 2021-11-15 at 17 03 07](https://user-images.githubusercontent.com/12445213/141814134-b17d1b90-8ebb-4ee1-98f2-70b411ca36c3.png)

2021-11-17 10:35 UTC, claudenirmf approved these changes

2021-11-17 10:35 UTC, merged